# Generated by Django 4.0.3 on 2022-03-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrimerEntrega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='matricula',
            field=models.IntegerField(default=None),
        ),
    ]
