# Generated by Django 4.0.3 on 2022-04-18 20:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrimerEntrega', '0002_especialista_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='comentarios',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
