# Generated by Django 4.0.3 on 2022-04-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatar',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='useravatar',
            name='more_description',
            field=models.CharField(default='Some String', max_length=100),
        ),
    ]
